/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Shift } from "./Shift";
import { ShiftCountArgs } from "./ShiftCountArgs";
import { ShiftFindManyArgs } from "./ShiftFindManyArgs";
import { ShiftFindUniqueArgs } from "./ShiftFindUniqueArgs";
import { CreateShiftArgs } from "./CreateShiftArgs";
import { UpdateShiftArgs } from "./UpdateShiftArgs";
import { DeleteShiftArgs } from "./DeleteShiftArgs";
import { ShiftService } from "../shift.service";
@graphql.Resolver(() => Shift)
export class ShiftResolverBase {
  constructor(protected readonly service: ShiftService) {}

  async _shiftsMeta(
    @graphql.Args() args: ShiftCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Shift])
  async shifts(@graphql.Args() args: ShiftFindManyArgs): Promise<Shift[]> {
    return this.service.shifts(args);
  }

  @graphql.Query(() => Shift, { nullable: true })
  async shift(
    @graphql.Args() args: ShiftFindUniqueArgs
  ): Promise<Shift | null> {
    const result = await this.service.shift(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Shift)
  async createShift(@graphql.Args() args: CreateShiftArgs): Promise<Shift> {
    return await this.service.createShift({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Shift)
  async updateShift(
    @graphql.Args() args: UpdateShiftArgs
  ): Promise<Shift | null> {
    try {
      return await this.service.updateShift({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Shift)
  async deleteShift(
    @graphql.Args() args: DeleteShiftArgs
  ): Promise<Shift | null> {
    try {
      return await this.service.deleteShift(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
